### ISSUE TITLE
Add support for multi-height experiments

### ISSUE THREAD

**Issue by adizere** [mikanikos/Fork-Accountability#7]

**Comment by mikanikos** [comment]
If I understood correctly, we want to support multi-height experiments in order to run the monitor algorithm for different heights. Do we just want to support the selection of a specific height from the monitor and run the algorithm on the HeightVoteSets for that specific height or do we want to run the monitor on multiple heights in the same execution? I believe the first one would be more appropriate since the second one can be achieved by simply having a script that executes the program on different input parameters @adizere @jovankomatovic5

**Comment by jovankomatovic5** [comment]
What you say makes sense to me.
In any case, this seems like a tiny detail, but I agree that first approach is fine.

**Comment by adizere** [comment]
> Do we just want to support the selection of a specific height from the monitor and run the algorithm on the HeightVoteSets for that specific height

Agree with you, this first option makes more sense.
